# Generated by Django 4.0.4 on 2022-05-03 00:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=120, null=True, verbose_name='Subtítulo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('mision', models.TextField(blank=True, null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Visión')),
                ('image', models.ImageField(help_text='Resolución Recomendada: 992x950', upload_to='aboutus', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Baner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtítulo')),
                ('image', models.ImageField(help_text='Resolución Recomendada: 1920x688', upload_to='baner', verbose_name='Baner')),
                ('youtube_video', models.URLField(blank=True, help_text='Ejemplo: https://www.youtube.com/watch?v=7GWKv03Osek', null=True, verbose_name='Video Youtube')),
            ],
            options={
                'verbose_name': 'Baner',
                'verbose_name_plural': 'Baners',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('address', models.CharField(help_text='Ejemplo: A108 Adam Street New York, NY 535022 United States', max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(help_text='Ejemplo: correo@mail.com', max_length=254, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(help_text='Ejemplo: +53 47281930', max_length=10, verbose_name='Número de teléfono')),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Informaciones de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Este campo es generado automáticamente', verbose_name='Nombre URL')),
                ('short_description', models.CharField(max_length=100, verbose_name='Pequeña Descripción')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('show', models.BooleanField(default=False, help_text='Chequear para mostrar en la página', verbose_name='Mostrar')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LI', 'LinkedIn')], default='FB', max_length=2)),
                ('url', models.URLField(help_text='Ejemplo: https://www.twitter.com/', verbose_name='Dirección URL')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('position', models.CharField(max_length=50, verbose_name='Posición')),
                ('list_order', models.IntegerField(default=1, help_text='Posición en la página principal. De menor a mayor.', verbose_name='Posición en la lista')),
                ('image', models.ImageField(help_text='Resolución Recomendada: 600x600', upload_to='team', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros',
                'ordering': ['list_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('LI', 'LinkedIn')], default='FB', max_length=2, verbose_name='Nombre')),
                ('url', models.URLField(help_text='Ejemplo: https://www.twitter.com/', verbose_name='Dirección URL')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member_socials', to='main.teammember', verbose_name='Miembro del equipo')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
