# Generated by Django 4.0.4 on 2022-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(help_text='Dirección de la empresa', max_length=100, verbose_name='Dirección')),
                ('email', models.EmailField(help_text='Ejemplo: correo@mail.com', max_length=254, verbose_name='Correo Electrónico')),
                ('phone_number', models.IntegerField(help_text='Ejemplo: +53 47281930', verbose_name='Número de teléfono')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LI', 'LinkedIn')], default='FB', max_length=2)),
                ('url', models.URLField(help_text='Ejemplo: https://www.twitter.com/', verbose_name='Dirección URL')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
