# Generated by Django 4.0.4 on 2022-05-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='Ejemplo: +53 47281930', max_length=10, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Útima actualización'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Útima actualización'),
        ),
    ]
