# Generated by Django 4.0.4 on 2022-05-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show',
            field=models.BooleanField(default=False, help_text='Chequear para mostrar en la página', verbose_name='Mostrar'),
        ),
    ]
