# Generated by Django 4.0.4 on 2022-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutus_mision_aboutus_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='mision',
            field=models.TextField(blank=True, null=True, verbose_name='Misión'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='vision',
            field=models.TextField(blank=True, null=True, verbose_name='Visión'),
        ),
    ]
