# Generated by Django 4.0.4 on 2022-05-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutus_mision_alter_aboutus_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('position', models.CharField(max_length=50, verbose_name='Posición')),
                ('list_order', models.IntegerField(default=1, help_text='Posición en la página principal. De menor a mayor.', verbose_name='Posición en la lista')),
                ('image', models.ImageField(help_text='Resolución Recomendada: 600x600', upload_to='team', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima Actualización')),
                ('name', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LI', 'LinkedIn')], default='FB', max_length=2)),
                ('url', models.URLField(help_text='Ejemplo: https://www.twitter.com/', verbose_name='Dirección URL')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teammember', verbose_name='Miembro del equipo')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
            },
        ),
    ]
