# Generated by Django 4.0.4 on 2022-05-02 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teammember_teammembersocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembersocial',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='main.teammember', verbose_name='Miembro del equipo'),
        ),
    ]
