# Generated by Django 4.0.4 on 2022-05-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_teammembersocial_team_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['list_order'], 'verbose_name': 'Miembro del Equipo', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AlterField(
            model_name='teammembersocial',
            name='name',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('YT', 'Youtube'), ('LI', 'LinkedIn')], default='FB', max_length=2, verbose_name='Nombre'),
        ),
    ]
