# Generated by Django 4.0.4 on 2022-05-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_teammembersocial_team_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembersocial',
            name='name',
            field=models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('LI', 'LinkedIn')], default='FB', max_length=2, verbose_name='Nombre'),
        ),
    ]
